"""
Agent Code Generator
Generates Python code for new agents.
"""
from typing import List
from loguru import logger
from datetime import datetime

from .models import AgentSpec, GeneratedCode


class CodeGenerator:
    """
    Generates Python code for new agents based on specifications.
    """
    
    def __init__(self):
        self.logger = logger.bind(component="code_generator")
    
    def generate(self, spec: AgentSpec) -> GeneratedCode:
        """
        Generate all code files for an agent.
        
        Args:
            spec: Agent specification
            
        Returns:
            GeneratedCode with all file contents
        """
        self.logger.info(f"Generating code for {spec.name}...")
        
        agent_file = self._generate_agent_class(spec)
        init_file = self._generate_init(spec)
        documentation = self._generate_documentation(spec)
        
        models_file = None
        if spec.inputs or spec.outputs:
            models_file = self._generate_models(spec)
        
        test_file = self._generate_tests(spec)
        
        return GeneratedCode(
            agent_file=agent_file,
            models_file=models_file,
            init_file=init_file,
            documentation=documentation,
            test_file=test_file
        )
    
    def _generate_agent_class(self, spec: AgentSpec) -> str:
        """Generate the main agent class file."""
        
        # Generate action methods
        action_methods = []
        action_dispatch_cases = []
        
        first_action = spec.actions[0]["name"] if spec.actions else "default"
        
        for i, action in enumerate(spec.actions):
            action_name = action["name"]
            action_desc = action.get("description", f"Execute {action_name}")
            
            # Method signature
            method = f'''
    async def _action_{action_name}(self, payload: Dict[str, Any]) -> AgentResult:
        """
        {action_desc}
        """
        self.logger.info(f"Executing {action_name}...")
        
        # TODO: Implement {action_name} logic
        
        return AgentResult(
            success=True,
            data={{"action": "{action_name}", "message": "Not yet implemented"}}
        )'''
            action_methods.append(method)
            
            # Dispatch case (skip first one as it's the default)
            if i > 0:
                dispatch = f'''            elif action == "{action_name}":
                return await self._action_{action_name}(payload)'''
                action_dispatch_cases.append(dispatch)
        
        # Build dispatch block
        dispatch_block = ""
        if action_dispatch_cases:
            dispatch_block = "\n" + "\n".join(action_dispatch_cases)
        
        # Build capabilities list as string
        capabilities_str = str(spec.capabilities)
        
        # Build full file
        code = f'''"""
{spec.name} Agent
{spec.description}

Generated by Meta Builder on {datetime.now().strftime('%Y-%m-%d')}
"""
from typing import Dict, Any
from loguru import logger

from agents.base_agent import BaseAgent, AgentResult


class {spec.name}Agent(BaseAgent):
    """
    {spec.purpose}
    """
    
    def __init__(self):
        super().__init__("{spec.name.upper()}", version="{spec.version}")
    
    async def execute(self, payload: Dict[str, Any]) -> AgentResult:
        """Execute agent task based on action."""
        action = payload.get("action", "{first_action}")
        
        self.logger.info(f"Executing action: {{action}}")
        
        try:
            if action == "{first_action}":
                return await self._action_{first_action}(payload){dispatch_block}
            else:
                return AgentResult(
                    success=False,
                    error=f"Unknown action: {{action}}"
                )
        except Exception as e:
            self.logger.error(f"Action {{action}} failed: {{e}}")
            return AgentResult(success=False, error=str(e))
{"".join(action_methods)}

    def get_capabilities(self) -> list:
        return {capabilities_str}
'''
        
        return code
    
    def _generate_init(self, spec: AgentSpec) -> str:
        """Generate __init__.py file."""
        return f'''"""
{spec.name} Agent Package
"""
from .agent import {spec.name}Agent

__all__ = ["{spec.name}Agent"]
'''
    
    def _generate_models(self, spec: AgentSpec) -> str:
        """Generate models file if needed."""
        
        models = [f'''"""
Data Models for {spec.name} Agent
"""
from pydantic import BaseModel
from typing import Optional, List, Dict
from datetime import datetime

''']
        
        # Generate input models
        for inp in spec.inputs:
            model_name = self._to_pascal_case(inp["name"])
            models.append(f'''
class {model_name}Input(BaseModel):
    """{inp.get("description", "")}"""
    # TODO: Define fields based on type: {inp.get("type", "Any")}
    pass
''')
        
        # Generate output models
        for out in spec.outputs:
            model_name = self._to_pascal_case(out["name"])
            models.append(f'''
class {model_name}Output(BaseModel):
    """{out.get("description", "")}"""
    # TODO: Define fields based on type: {out.get("type", "Any")}
    pass
''')
        
        return "".join(models)
    
    def _generate_tests(self, spec: AgentSpec) -> str:
        """Generate test file."""
        
        test_cases = []
        for action in spec.actions:
            action_name = action["name"]
            test_cases.append(f'''
@pytest.mark.asyncio
async def test_{action_name}():
    """Test {action_name} action."""
    agent = {spec.name}Agent()
    result = await agent.execute({{"action": "{action_name}"}})
    assert result.success
''')
        
        return f'''"""
Tests for {spec.name} Agent
"""
import pytest
from .agent import {spec.name}Agent


@pytest.fixture
def agent():
    return {spec.name}Agent()


@pytest.mark.asyncio
async def test_agent_initialization(agent):
    """Test agent initializes correctly."""
    assert agent.name == "{spec.name.upper()}"
    assert agent.version == "{spec.version}"


@pytest.mark.asyncio
async def test_get_capabilities(agent):
    """Test capabilities are returned."""
    caps = agent.get_capabilities()
    assert isinstance(caps, list)
    assert len(caps) > 0
{"".join(test_cases)}
'''
    
    def _generate_documentation(self, spec: AgentSpec) -> str:
        """Generate agent documentation."""
        
        # Format actions
        actions_doc = []
        for action in spec.actions:
            params = action.get("parameters", [])
            params_str = ", ".join(
                f"`{p['name']}` ({p.get('type', 'any')})" 
                for p in params
            ) if params else "None"
            
            actions_doc.append(f'''
### {action["name"]}

{action.get("description", "No description")}

**Parameters:** {params_str}

**Returns:** {action.get("returns", "AgentResult")}
''')
        
        # Format capabilities
        capabilities_list = "\n".join(f"- {c}" for c in spec.capabilities) if spec.capabilities else "- None defined"
        
        # Format inputs
        inputs_list = "\n".join(
            f"- **{i['name']}** ({i.get('type', 'any')}): {i.get('description', '')}" 
            for i in spec.inputs
        ) if spec.inputs else "No specific inputs required"
        
        # Format outputs
        outputs_list = "\n".join(
            f"- **{o['name']}** ({o.get('type', 'any')}): {o.get('description', '')}" 
            for o in spec.outputs
        ) if spec.outputs else "Standard AgentResult"
        
        # Format dependencies
        deps_list = "\n".join(spec.dependencies) if spec.dependencies else "No additional dependencies"
        
        # Trigger config
        trigger_config_str = f"\n**Trigger Config:** {spec.trigger_config}" if spec.trigger_config else ""
        
        return f'''# AGENT: {spec.name.upper()}
## {spec.description}

```
Agent ID: {spec.name.upper()}
Location: {spec.location.value}
Trigger: {spec.trigger_type.value}
Version: {spec.version}
```

---

## PURPOSE

{spec.purpose}

---

## CAPABILITIES

{capabilities_list}

---

## ACTIONS

{"".join(actions_doc)}

---

## INPUTS

{inputs_list}

---

## OUTPUTS

{outputs_list}

---

## DEPENDENCIES

```
{deps_list}
```

---

## CONFIGURATION

**Trigger Type:** {spec.trigger_type.value}{trigger_config_str}

---

*Generated by Meta Builder*
*Version: {spec.version}*
'''
    
    def _to_pascal_case(self, name: str) -> str:
        """Convert snake_case or space-separated name to PascalCase."""
        # Replace underscores and spaces with space, then title case, then remove spaces
        words = name.replace("_", " ").replace("-", " ").split()
        return "".join(word.capitalize() for word in words)

