"""
Context Manager
Maintains complete project knowledge base for AI prompts and development.
"""
import json
from pathlib import Path
from typing import Dict, Any, Optional, List
from loguru import logger

from .models import IdeaAnalysis, TechStackRecommendation, ProjectArchitecture, ProjectContext


class ContextManager:
    """
    Manages project context throughout the development lifecycle.
    """

    def __init__(self, project_path: str = None):
        self.project_path = Path(project_path) if project_path else None
        self.logger = logger.bind(component="context_manager")
        self._context = ProjectContext()

    def initialize_context(
        self,
        analysis: IdeaAnalysis,
        tech_stack: TechStackRecommendation,
        architecture: ProjectArchitecture
    ) -> str:
        """
        Initialize project context from analysis results.

        Args:
            analysis: Project analysis
            tech_stack: Recommended tech stack
            architecture: System architecture

        Returns:
            Complete project context as markdown string
        """
        self.logger.info("Initializing project context...")

        # Build comprehensive context
        context_md = f"""# {analysis.title} - Project Context

## Overview
**Description:** {analysis.description}
**Problem Statement:** {analysis.problem_statement}
**Target User:** {analysis.target_user}
**Value Proposition:** {analysis.value_proposition}

**Project Type:** {analysis.project_type.value if hasattr(analysis.project_type, 'value') else analysis.project_type}
**Project Size:** {analysis.project_size.value if hasattr(analysis.project_size, 'value') else analysis.project_size}
**Estimated Hours:** {analysis.estimated_hours}
**Full-Stack:** {"Yes" if analysis.is_fullstack else "No"}

## Tech Stack

### Frontend
{self._format_tech_stack(tech_stack.frontend)}

### Backend
{self._format_tech_stack(tech_stack.backend)}

### Infrastructure
{self._format_tech_stack(tech_stack.infrastructure)}

**Reasoning:** {tech_stack.reasoning}

## Architecture Overview
{architecture.overview}

### Components
{chr(10).join(f"- **{comp.get('name', 'Unknown')}**: {comp.get('purpose', 'Unknown purpose')}" for comp in architecture.components)}

### Data Flow
{architecture.data_flow}

## API Endpoints
{chr(10).join(f"- `{endpoint.get('method', 'GET')} {endpoint.get('path', '/unknown')}`: {endpoint.get('description', 'No description')}" for endpoint in architecture.api_endpoints)}

## Data Models
{chr(10).join(f"- **{model.get('name', 'Unknown')}**: {model.get('fields', 'No fields')} | Relations: {model.get('relationships', 'None')}" for model in architecture.data_models)}

## Diagrams

### System Architecture
```
{architecture.diagrams.get('system_diagram', 'No diagram available')}
```

### Data Flow
```
{architecture.diagrams.get('data_flow', 'No diagram available')}
```

## Development Phases
*To be populated during phase execution*

## Testing Strategy
*To be populated during implementation*

## Deployment Plan
*To be populated during production preparation*

---
*Generated by Ideas Machine - {analysis.title}*
"""

        # Update internal context
        self._context = ProjectContext(
            architecture={
                "overview": architecture.overview,
                "components": architecture.components,
                "data_flow": architecture.data_flow,
                "diagrams": architecture.diagrams
            },
            models=architecture.data_models,
            endpoints=architecture.api_endpoints,
            components=[],  # Will be populated during development
            test_coverage={}  # Will be populated during testing
        )

        return context_md

    def update_context_after_phase(
        self,
        phase_name: str,
        phase_result: Dict[str, Any],
        new_files: list = None,
        new_components: list = None
    ) -> str:
        """
        Update context after completing a development phase.

        Args:
            phase_name: Name of the completed phase
            phase_result: Results from phase execution
            new_files: New files created in this phase
            new_components: New components implemented

        Returns:
            Updated context markdown
        """
        self.logger.info(f"Updating context after phase: {phase_name}")

        # Update internal context
        if new_components:
            self._context.components.extend(new_components)

        if "test_results" in phase_result:
            self._context.test_coverage[phase_name] = phase_result["test_results"]

        # Generate updated markdown
        # This would append to existing PROJECT_CONTEXT.md
        phase_update = f"""

## Phase Complete: {phase_name}

### Results
- **Success:** {phase_result.get('success', False)}
- **Files Generated:** {len(new_files) if new_files else 0}
- **Components Added:** {len(new_components) if new_components else 0}

### Files Created
{chr(10).join(f"- {file}" for file in (new_files or []))}

### Components Implemented
{chr(10).join(f"- {comp}" for comp in (new_components or []))}

### Test Results
{json.dumps(phase_result.get('test_results', {}), indent=2)}

### Errors & Fixes
{chr(10).join(f"- {error}" for error in phase_result.get('errors', []))}
{chr(10).join(f"- **Fixed:** {fix['fix_description']}" for fix in phase_result.get('fixes_applied', []))}
"""

        return phase_update

    def get_context_for_ai_prompt(self, current_phase: str = None) -> Dict[str, Any]:
        """
        Get context optimized for AI prompts.

        Args:
            current_phase: Current development phase (for filtering relevant context)

        Returns:
            Context dictionary suitable for AI prompts
        """
        context = {
            "architecture": self._context.architecture,
            "models": self._context.models,
            "endpoints": self._context.endpoints,
            "components": self._context.components,
            "test_coverage": self._context.test_coverage
        }

        # Filter context based on current phase if specified
        if current_phase:
            # Phase-specific filtering logic could go here
            pass

        return context

    def get_relevant_context(self, query: str, max_items: int = 5) -> Dict[str, Any]:
        """
        Get context most relevant to a specific query.

        Args:
            query: Search query
            max_items: Maximum items to return per category

        Returns:
            Filtered context dictionary
        """
        # Simple keyword matching for now
        # Could be enhanced with semantic search using the RAG system
        query_lower = query.lower()

        relevant_endpoints = [
            endpoint for endpoint in self._context.endpoints[:max_items]
            if any(keyword in json.dumps(endpoint).lower() for keyword in query_lower.split())
        ]

        relevant_models = [
            model for model in self._context.models[:max_items]
            if any(keyword in json.dumps(model).lower() for keyword in query_lower.split())
        ]

        relevant_components = [
            comp for comp in self._context.components[:max_items]
            if any(keyword in json.dumps(comp).lower() for keyword in query_lower.split())
        ]

        return {
            "endpoints": relevant_endpoints,
            "models": relevant_models,
            "components": relevant_components,
            "architecture": self._context.architecture
        }

    async def store_successful_template(
        self,
        template_data: Dict[str, Any],
        analysis: 'IdeaAnalysis',
        tech_stack: 'TechStackRecommendation'
    ) -> bool:
        """
        Store a successful project implementation as a reusable template.

        Args:
            template_data: Template data including code patterns, successful approaches
            analysis: Project analysis that was successful
            tech_stack: Tech stack that worked well

        Returns:
            True if stored successfully
        """
        try:
            # Import here to avoid circular imports and handle missing cloud API
            try:
                from app.rag.knowledge_base import get_knowledge_base
            except ImportError:
                self.logger.info("RAG knowledge base not available (running in local mode), skipping template storage")
                return True  # Return True to indicate "successfully skipped"

            kb = get_knowledge_base()

            # Create template document
            template_doc = {
                "title": f"Template: {analysis.project_type.value if hasattr(analysis.project_type, 'value') else analysis.project_type} - {analysis.title}",
                "content": f"""
# Successful {analysis.project_type.value if hasattr(analysis.project_type, 'value') else analysis.project_type} Implementation

**Project:** {analysis.title}
**Problem Solved:** {analysis.problem_statement}
**Target Users:** {analysis.target_user}
**Success Metrics:** {analysis.value_proposition}

## Tech Stack (Proven)
Frontend: {', '.join(tech_stack.frontend.values())}
Backend: {', '.join(tech_stack.backend.values())}
Infrastructure: {', '.join(tech_stack.infrastructure.values())}

## Key Patterns & Solutions

{json.dumps(template_data, indent=2)}

## Lessons Learned
- This tech stack combination worked well for {analysis.project_type.value if hasattr(analysis.project_type, 'value') else analysis.project_type} projects
- Estimated {analysis.estimated_hours} hours for similar scope
- Full-stack approach: {'Recommended' if analysis.is_fullstack else 'Optional'}

## Reuse Guidelines
Use this template for projects with similar:
- Problem domain: {analysis.problem_statement[:100]}...
- Technical complexity: {analysis.project_size.value if hasattr(analysis.project_size, 'value') else analysis.project_size}
- User requirements: {analysis.target_user}
""",
                "source": "TEMPLATE_SUCCESS",
                "tags": [
                    "template",
                    analysis.project_type.value if hasattr(analysis.project_type, 'value') else str(analysis.project_type),
                    analysis.project_size.value if hasattr(analysis.project_size, 'value') else str(analysis.project_size),
                    "successful_implementation",
                    "reusable_pattern"
                ],
                "metadata": {
                    "project_type": analysis.project_type.value if hasattr(analysis.project_type, 'value') else str(analysis.project_type),
                    "project_size": analysis.project_size.value if hasattr(analysis.project_size, 'value') else str(analysis.project_size),
                    "estimated_hours": analysis.estimated_hours,
                    "is_fullstack": analysis.is_fullstack,
                    "tech_stack": {
                        "frontend": tech_stack.frontend,
                        "backend": tech_stack.backend,
                        "infrastructure": tech_stack.infrastructure
                    },
                    "success_patterns": template_data
                }
            }

            result = await kb.add_document(
                content=template_doc["content"],
                source=template_doc["source"],
                title=template_doc["title"],
                tags=template_doc["tags"],
                metadata=template_doc["metadata"]
            )

            self.logger.info(f"Stored successful template: {template_doc['title']}")
            return True

        except Exception as e:
            self.logger.error(f"Failed to store template: {e}")
            return False

    async def get_similar_templates(
        self,
        analysis: 'IdeaAnalysis',
        tech_stack: 'TechStackRecommendation',
        limit: int = 3
    ) -> List[Dict[str, Any]]:
        """
        Retrieve similar successful templates for guidance.

        Args:
            analysis: Current project analysis
            tech_stack: Proposed tech stack
            limit: Maximum templates to return

        Returns:
            List of similar successful templates
        """
        try:
            # Import here to avoid circular imports and handle missing cloud API
            try:
                from app.rag.knowledge_base import get_knowledge_base
            except ImportError:
                self.logger.info("RAG knowledge base not available (running in local mode), returning empty templates")
                return []  # Return empty list when RAG is not available

            kb = get_knowledge_base()

            # Search for similar templates
            query = f"""
            {analysis.project_type.value if hasattr(analysis.project_type, 'value') else analysis.project_type}
            {analysis.problem_statement}
            {analysis.target_user}
            successful implementation template
            """

            results = await kb.search(
                query=query,
                limit=limit,
                source_filter="TEMPLATE_SUCCESS",
                tag_filter=[
                    analysis.project_type.value if hasattr(analysis.project_type, 'value') else str(analysis.project_type),
                    "successful_implementation"
                ]
            )

            return results

        except Exception as e:
            self.logger.error(f"Failed to retrieve similar templates: {e}")
            return []

    def save_context_to_file(self, context_md: str, filename: str = "PROJECT_CONTEXT.md") -> bool:
        """
        Save context to file in project directory.

        Args:
            context_md: Context markdown content
            filename: Filename to save as

        Returns:
            True if saved successfully
        """
        if not self.project_path:
            self.logger.warning("No project path set, cannot save context file")
            return False

        try:
            context_file = self.project_path / filename
            context_file.parent.mkdir(parents=True, exist_ok=True)

            with open(context_file, 'w', encoding='utf-8') as f:
                f.write(context_md)

            self.logger.info(f"Context saved to {context_file}")
            return True

        except Exception as e:
            self.logger.error(f"Failed to save context file: {e}")
            return False

    def _format_tech_stack(self, tech_stack: Dict[str, str]) -> str:
        """Format tech stack dictionary as markdown."""
        if not tech_stack:
            return "Not specified"

        return chr(10).join(f"- **{key}**: {value}" for key, value in tech_stack.items())
