"""
Documentation Generator
Creates comprehensive documentation for projects and phases.
"""
import json
from pathlib import Path
from typing import Dict, Any, List
from loguru import logger

from .models import (
    IdeaAnalysis, TechStackRecommendation, ProjectArchitecture,
    PhaseSpec, ProjectContext
)


class DocumentationGenerator:
    """
    Generates comprehensive documentation for projects and development phases.
    """

    def __init__(self, project_path: str = None):
        self.project_path = Path(project_path) if project_path else Path.cwd()
        self.logger = logger.bind(component="doc_generator")

    def generate_master_plan(
        self,
        analysis: IdeaAnalysis,
        tech_stack: TechStackRecommendation,
        architecture: ProjectArchitecture,
        phases: List[PhaseSpec]
    ) -> str:
        """
        Generate master project plan document.

        Args:
            analysis: Project analysis
            tech_stack: Recommended tech stack
            architecture: System architecture
            phases: Planned development phases

        Returns:
            Complete master plan markdown
        """
        return f"""# {analysis.title} — Master Plan

## Vision
{analysis.description}

**Problem Statement:** {analysis.problem_statement}
**Target User:** {analysis.target_user}
**Value Proposition:** {analysis.value_proposition}

## Project Overview

- **Type:** {analysis.project_type.value if hasattr(analysis.project_type, 'value') else analysis.project_type}
- **Size:** {analysis.project_size.value if hasattr(analysis.project_size, 'value') else analysis.project_size}
- **Estimated Hours:** {analysis.estimated_hours}
- **Full-Stack:** {"Yes" if analysis.is_fullstack else "No"}

## Tech Stack

### Frontend
{chr(10).join(f"- **{k}:** {v}" for k, v in tech_stack.frontend.items())}

### Backend
{chr(10).join(f"- **{k}:** {v}" for k, v in tech_stack.backend.items())}

### Infrastructure
{chr(10).join(f"- **{k}:** {v}" for k, v in tech_stack.infrastructure.items())}

**Reasoning:** {tech_stack.reasoning}

## Architecture Overview
{architecture.overview}

### System Components
{chr(10).join(f"- **{comp.get('name', 'Unknown')}**: {comp.get('purpose', 'Unknown purpose')}" for comp in architecture.components)}

### Data Flow
{architecture.data_flow}

## Development Phases

{chr(10).join(f"### Phase {phase.phase_number}: {phase.phase_name}{chr(10)}**Duration:** {phase.duration}{chr(10)}**Goal:** {phase.goal}{chr(10)}{chr(10)}**Key Features:**{chr(10)}{chr(10).join(f'- {feature}' for feature in phase.features[:3])}{chr(10)}{chr(10)}**Success Criteria:**{chr(10)}{chr(10).join(f'- {criterion}' for criterion in phase.success_criteria)}{chr(10)}" for phase in phases)}

## Success Metrics

- **User Engagement:** Measure based on {analysis.value_proposition.lower()}
- **Technical Performance:** All phases complete with passing tests
- **Code Quality:** Comprehensive test coverage and documentation
- **Time to MVP:** Complete Phase 1-3 within estimated timeline

## Risk Mitigation

{chr(10).join(f"- **{risk}**: Mitigated through careful planning and iterative development" for risk in analysis.risks)}

## Non-Goals

{chr(10).join(f"- {assumption}" for assumption in analysis.assumptions)}

---
*Generated by Ideas Machine - {analysis.title}*
*Last Updated: Auto-generated during project scaffolding*
"""

    def generate_phase_specification(
        self,
        phase: PhaseSpec,
        analysis: IdeaAnalysis,
        tech_stack: TechStackRecommendation,
        architecture: ProjectArchitecture,
        context: ProjectContext
    ) -> str:
        """
        Generate detailed phase specification document.

        Args:
            phase: Phase to document
            analysis: Project analysis
            tech_stack: Tech stack
            architecture: Architecture
            context: Current project context

        Returns:
            Complete phase specification markdown
        """
        phase_filename = "02d"

        return f"""# Phase {phase.phase_number}: {phase.phase_name}
## {analysis.title} - Development Specification

```
╔═══════════════════════════════════════════════════════════════════════════════╗
║  PHASE {phase.phase_number}: {phase.phase_name.upper():<60} ║
║  Duration: {phase.duration:<63} ║
║  Prerequisites: Phase {phase.phase_number - 1 if phase.phase_number > 1 else 'None':<54} ║
╚═══════════════════════════════════════════════════════════════════════════════╝
```

---

## OBJECTIVES

- [ ] {phase.goal}
{chr(10).join(f"- [ ] {feature}" for feature in phase.features)}

---

## ARCHITECTURE CONTEXT

### Current System State
{architecture.overview}

### Components to Implement
{chr(10).join(f"- [ ] {comp.get('name', 'Unknown')}: {comp.get('purpose', 'Unknown purpose')}" for comp in architecture.components)}

### Data Models
{chr(10).join(f"- **{model.get('name', 'Unknown')}**: {model.get('fields', 'No fields')}" for model in architecture.data_models)}

---

## DETAILED REQUIREMENTS

### User Stories
{chr(10).join(f"#### {i+1}. {story}" for i, story in enumerate(phase.user_stories))}

### Technical Tasks
{chr(10).join(f"#### {task.task_id.replace('_', ' ').title()}{chr(10)}**Description:** {task.description}{chr(10)}{chr(10)}**Deliverables:**{chr(10)}{chr(10).join(f'- {d}' for d in task.deliverables)}{chr(10)}{chr(10)}**Dependencies:**{chr(10)}{chr(10).join(f'- {d}' for d in task.dependencies) if task.dependencies else '- None'}{chr(10)}{chr(10)}**Test Requirements:**{chr(10)}{chr(10).join(f'- {t}' for t in task.test_requirements)}{chr(10)}" for task in phase.tasks)}

---

## UI SPECIFICATIONS

### Mockups
```
{phase.ui_mockups or 'No UI mockups provided for this phase'}
```

### Design System
- **Colors:** Based on project theme
- **Typography:** System fonts with fallbacks
- **Spacing:** Consistent 4px grid system
- **Components:** Reusable design system components

---

## API SPECIFICATIONS

### Endpoints to Implement
{chr(10).join(f"#### `{endpoint.get('method', 'GET')} {endpoint.get('path', '/unknown')}`{chr(10)}**Description:** {endpoint.get('description', 'No description')}{chr(10)}{chr(10)}**Request/Response:**{chr(10)}```json{chr(10)}// TODO: Define request/response schemas{chr(10)}```{chr(10)}" for endpoint in phase.api_endpoints)}

### Data Contracts
{chr(10).join(f"#### {model.get('name', 'Unknown')} Model{chr(10)}**Fields:** {model.get('fields', 'No fields specified')}{chr(10)}**Relationships:** {model.get('relationships', 'None')}{chr(10)}{chr(10)}**Schema:**{chr(10)}```json{chr(10)}{{{chr(10)}  // TODO: Define JSON schema{chr(10)}}}{chr(10)}```{chr(10)}" for model in architecture.data_models)}

---

## DATABASE CHANGES

### Schema Updates
{chr(10).join(f"- [ ] {change}" for change in phase.database_changes)}

### Migration Scripts
```sql
-- TODO: Add migration scripts for this phase
```

### Indexes and Constraints
```sql
-- TODO: Define indexes and constraints
```

---

## TESTING REQUIREMENTS

### Unit Tests
{chr(10).join(f"- [ ] {test}" for test in phase.test_commands if 'unit' in test.lower())}

### Integration Tests
{chr(10).join(f"- [ ] {test}" for test in phase.test_commands if 'integration' in test.lower())}

### E2E Tests
{chr(10).join(f"- [ ] {test}" for test in phase.test_commands if 'e2e' in test.lower())}

---

## SUCCESS CRITERIA

{chr(10).join(f"### {i+1}. {criterion}{chr(10)}**Status:** [ ] Not Started  [ ] In Progress  [ ] Completed{chr(10)}{chr(10)}**Verification:**{chr(10)}{chr(10)}**Notes:**{chr(10)}{chr(10)}---{chr(10)}" for i, criterion in enumerate(phase.success_criteria))}

---

## IMPLEMENTATION NOTES

### Tech Stack Specifics
- **Frontend:** {tech_stack.frontend.get('framework', 'Not specified')}
- **Backend:** {tech_stack.backend.get('framework', 'Not specified')}
- **Database:** {tech_stack.backend.get('database', 'Not specified')}

### Development Commands
```bash
# Setup
{chr(10).join(f"# {cmd}" for cmd in phase.test_commands)}

# Testing
{chr(10).join(phase.test_commands)}
```

### File Structure
```
project/
├── # Files to create/modify in this phase
{chr(10).join(f"├── # TODO: {task.task_id}" for task in phase.tasks)}
└── # Existing files that may be referenced
```

---

## NEXT PHASE

Once all success criteria are met, proceed to **[PHASE_{phase.phase_number + 1}_DETAILS.md](./PHASE_{phase.phase_number + 1}_DETAILS.md)**

---

**Phase {phase.phase_number} Complete Criteria:**
{chr(10).join(f"- {criterion}" for criterion in phase.success_criteria)}

---

*Generated by Ideas Machine - Phase {phase.phase_number} Specification*
*Last Updated: Auto-generated during phase planning*
"""

    def generate_api_documentation(
        self,
        analysis: IdeaAnalysis,
        architecture: ProjectArchitecture,
        context: ProjectContext
    ) -> str:
        """
        Generate API documentation.

        Args:
            analysis: Project analysis
            architecture: Architecture
            context: Current context

        Returns:
            API documentation markdown
        """
        return f"""# {analysis.title} - API Documentation

## Overview
{analysis.description}

**Base URL:** `http://localhost:8000/api/v1`
**Authentication:** Bearer token (JWT)

## Endpoints

{chr(10).join(f"### {endpoint.get('method', 'GET')} {endpoint.get('path', '/unknown')}{chr(10)}{chr(10)}**Description:** {endpoint.get('description', 'No description')}{chr(10)}{chr(10)}**Authentication:** Required{chr(10)}{chr(10)}**Request Body:**{chr(10)}```json{chr(10)}{{{chr(10)}  // TODO: Define request schema{chr(10)}}}{chr(10)}```{chr(10)}{chr(10)}**Response:**{chr(10)}```json{chr(10)}{{{chr(10)}  // TODO: Define response schema{chr(10)}}}{chr(10)}```{chr(10)}{chr(10)}**Error Responses:**{chr(10)}- `400`: Bad Request{chr(10)}- `401`: Unauthorized{chr(10)}- `404`: Not Found{chr(10)}- `500`: Internal Server Error{chr(10)}{chr(10)}---{chr(10)}" for endpoint in context.endpoints)}

## Data Models

{chr(10).join(f"### {model.get('name', 'Unknown')}{chr(10)}{chr(10)}**Fields:**{chr(10)}{chr(10).join(f'- `{field}`' for field in model.get('fields', '').split(', '))}{chr(10)}{chr(10)}**Relationships:**{chr(10)}{model.get('relationships', 'None')}{chr(10)}{chr(10)}**Example:**{chr(10)}```json{chr(10)}{{{chr(10)}  // TODO: Add example{chr(10)}}}{chr(10)}```{chr(10)}{chr(10)}---{chr(10)}" for model in context.models)}

## Authentication

### Login
```http
POST /auth/login
Content-Type: application/json

{{
  "email": "user@example.com",
  "password": "password"
}}
```

### Register
```http
POST /auth/register
Content-Type: application/json

{{
  "email": "user@example.com",
  "password": "password",
  "name": "User Name"
}}
```

## Error Handling

All endpoints return errors in the following format:

```json
{{
  "error": {{
    "code": "ERROR_CODE",
    "message": "Human readable error message",
    "details": {{
      // Additional error details
    }}
  }}
}}
```

## Rate Limiting

- **Authenticated requests:** 1000 requests per hour
- **Unauthenticated requests:** 100 requests per hour

## Versioning

API versioning is handled through URL paths (`/api/v1/`).

---
*Generated by Ideas Machine - API Documentation*
*Last Updated: Auto-generated*
"""

    def generate_readme(
        self,
        analysis: IdeaAnalysis,
        tech_stack: TechStackRecommendation,
        architecture: ProjectArchitecture
    ) -> str:
        """
        Generate project README.md.

        Args:
            analysis: Project analysis
            tech_stack: Tech stack
            architecture: Architecture

        Returns:
            README markdown
        """
        return f"""# {analysis.title}

{analysis.description}

## 🚀 Quick Start

### Prerequisites
- Node.js 18+ (frontend)
- Python 3.9+ (backend)
- PostgreSQL/MongoDB (database)

### Installation

1. **Clone and setup:**
   ```bash
   git clone <repository-url>
   cd {analysis.title.lower().replace(' ', '-')}
   ```

2. **Backend setup:**
   ```bash
   cd backend
   python -m venv venv
   source venv/bin/activate  # Windows: venv\\Scripts\\activate
   pip install -r requirements.txt
   cp .env.example .env
   # Edit .env with your database credentials
   ```

3. **Frontend setup:**
   ```bash
   cd frontend
   npm install
   cp .env.example .env.local
   # Edit .env.local with your API URL
   ```

4. **Database setup:**
   ```bash
   # Run migrations/setup scripts
   ```

### Running the Application

```bash
# Terminal 1: Backend
cd backend && python main.py

# Terminal 2: Frontend
cd frontend && npm run dev
```

Visit `http://localhost:3000` to see the application.

## 🏗️ Architecture

{architecture.overview}

### Tech Stack
- **Frontend:** {tech_stack.frontend.get('framework', 'Not specified')}
- **Backend:** {tech_stack.backend.get('framework', 'Not specified')}
- **Database:** {tech_stack.backend.get('database', 'Not specified')}
- **Deployment:** {tech_stack.infrastructure.get('hosting', 'Not specified')}

### Data Flow
{architecture.data_flow}

## 📁 Project Structure

```
{analysis.title.lower().replace(' ', '-')}/
├── frontend/              # React/Next.js application
│   ├── src/
│   │   ├── components/    # Reusable UI components
│   │   ├── pages/         # Application pages
│   │   ├── hooks/         # Custom React hooks
│   │   └── lib/           # Utilities and API clients
│   └── package.json
├── backend/               # FastAPI/Flask application
│   ├── app/
│   │   ├── models/        # Database models
│   │   ├── routes/        # API endpoints
│   │   ├── services/      # Business logic
│   │   └── main.py
│   └── requirements.txt
├── docs/                  # Documentation
├── docker-compose.yml     # Docker setup
└── README.md
```

## 🧪 Testing

```bash
# Backend tests
cd backend && pytest

# Frontend tests
cd frontend && npm test

# End-to-end tests
npm run test:e2e
```

## 🚀 Deployment

### Development
```bash
docker-compose up -d
```

### Production
```bash
# Frontend
cd frontend && npm run build && npm run start

# Backend
cd backend && gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker
```

## 📚 Documentation

- [API Documentation](./docs/API.md)
- [Architecture Overview](./docs/ARCHITECTURE.md)
- [Development Guide](./docs/DEVELOPMENT.md)

## 🤝 Contributing

1. Fork the repository
2. Create a feature branch (`git checkout -b feature/amazing-feature`)
3. Commit your changes (`git commit -m 'Add amazing feature'`)
4. Push to the branch (`git push origin feature/amazing-feature`)
5. Open a Pull Request

## 📝 License

This project is licensed under the MIT License - see the [LICENSE](LICENSE) file for details.

## 👥 Authors

- **Ideas Machine** - Auto-generated project scaffold

## 🙏 Acknowledgments

- Generated using Ideas Machine AI assistant
- Built with modern web technologies
- Following best practices for full-stack development

---

**Status:** 🚧 In Development
**Version:** 0.1.0
**Last Updated:** Auto-generated
"""

    def update_project_context(
        self,
        context_md: str,
        phase_result: Dict[str, Any],
        phase_name: str
    ) -> str:
        """
        Update PROJECT_CONTEXT.md with phase completion results.

        Args:
            context_md: Current context markdown
            phase_result: Results from phase execution
            phase_name: Name of completed phase

        Returns:
            Updated context markdown
        """
        phase_update = f"""

## Phase Complete: {phase_name}

### Results
- **Success:** {phase_result.get('success', False)}
- **Files Generated:** {len(phase_result.get('generated_files', []))}
- **Fixes Applied:** {len(phase_result.get('fixes_applied', []))}

### Test Results
{json.dumps(phase_result.get('test_results', {}), indent=2)}

### Errors & Fixes
{chr(10).join(f"- **Fixed:** {fix.get('description', 'Unknown fix')}" for fix in phase_result.get('fixes_applied', []))}

### Files Created
{chr(10).join(f"- `{file}`" for file in phase_result.get('generated_files', []))}
"""

        # Insert before the final "---" marker
        if "---" in context_md:
            parts = context_md.rsplit("---", 1)
            return parts[0] + phase_update + "\n---" + parts[1]
        else:
            return context_md + phase_update

    def generate_file_manifest(
        self,
        generated_files: Dict[str, str],
        analysis: IdeaAnalysis
    ) -> str:
        """
        Generate manifest of all generated files.

        Args:
            generated_files: Dictionary of generated files
            analysis: Project analysis

        Returns:
            File manifest markdown
        """
        files_by_type = {
            "frontend": [],
            "backend": [],
            "config": [],
            "docs": [],
            "tests": []
        }

        for file_path in generated_files.keys():
            if file_path.startswith("src/") or file_path.startswith("frontend/"):
                files_by_type["frontend"].append(file_path)
            elif file_path.startswith("app/") or file_path.startswith("backend/"):
                files_by_type["backend"].append(file_path)
            elif any(ext in file_path for ext in [".json", ".yml", ".yaml", ".env"]):
                files_by_type["config"].append(file_path)
            elif file_path.startswith("docs/"):
                files_by_type["docs"].append(file_path)
            elif "test" in file_path.lower():
                files_by_type["tests"].append(file_path)
            else:
                files_by_type["config"].append(file_path)

        return f"""# {analysis.title} - File Manifest

## Generated Files Overview

**Total Files:** {len(generated_files)}
**Generated:** {len(generated_files)} files
**Test Coverage:** {len(files_by_type['tests'])} test files

## File Breakdown

### Frontend Files ({len(files_by_type['frontend'])})
{chr(10).join(f"- `{file}`" for file in sorted(files_by_type['frontend']))}

### Backend Files ({len(files_by_type['backend'])})
{chr(10).join(f"- `{file}`" for file in sorted(files_by_type['backend']))}

### Configuration Files ({len(files_by_type['config'])})
{chr(10).join(f"- `{file}`" for file in sorted(files_by_type['config']))}

### Documentation ({len(files_by_type['docs'])})
{chr(10).join(f"- `{file}`" for file in sorted(files_by_type['docs']))}

### Test Files ({len(files_by_type['tests'])})
{chr(10).join(f"- `{file}`" for file in sorted(files_by_type['tests']))}

## Generation Summary

- **Project Type:** {analysis.project_type.value if hasattr(analysis.project_type, 'value') else analysis.project_type}
- **Full-Stack:** {"Yes" if analysis.is_fullstack else "No"}
- **Estimated Complexity:** {analysis.project_size.value if hasattr(analysis.project_size, 'value') else analysis.project_size}
- **Code Quality:** Production-ready with comprehensive testing

## Next Steps

1. **Review Generated Code:** Examine all generated files for correctness
2. **Run Tests:** Execute the test suite to verify functionality
3. **Manual Testing:** Test the application manually
4. **Deployment:** Set up production deployment pipeline
5. **Documentation:** Update documentation as needed

---
*Generated by Ideas Machine - File Manifest*
*Total Files: {len(generated_files)}*
"""
